### ISSUE TITLE
tslint failed

### ISSUE THREAD

**Issue by sguiheux** [edcarroll/ng2-semantic-ui#295]
### Bug description:
tslint command failed. Cannot use this lib because my build failed too because of the same errors

ng2-semantic-ui: master

Run :  tslint -c tslint.json --type-check --project src/tsconfig.json 

> 
Error at src/modules/datepicker/classes/calendar-mappings.ts:3:49: ',' expected.
Error at src/modules/datepicker/classes/calendar-mappings.ts:3:51: Duplicate identifier 'CalendarViewType'.
Error at src/modules/datepicker/classes/calendar-mappings.ts:8:20: Generic type 'CalendarMapping' requires 2 type argument(s).
Error at src/modules/datepicker/classes/calendar-mappings.ts:9:17: Generic type 'CalendarMapping' requires 2 type argument(s).
Error at src/modules/datepicker/classes/calendar-mappings.ts:3:49: ',' expected.
Error at src/modules/datepicker/classes/calendar-mappings.ts:3:51: Duplicate identifier 'CalendarViewType'.
Error at src/modules/datepicker/classes/calendar-mappings.ts:8:20: Generic type 'CalendarMapping' requires 2 type argument(s).
Error at src/modules/datepicker/classes/calendar-mappings.ts:9:17: Generic type 'CalendarMapping' requires 2 type argument(s).
Error at src/modules/datepicker/helpers/date-fns.ts:38:23: Type 'undefined' cannot be used as an index type.
Error at src/modules/datepicker/helpers/date-fns.ts:43:57: Type 'undefined' cannot be used as an index type.
Error at src/modules/datepicker/helpers/date-fns.ts:48:41: Type 'undefined' cannot be used as an index type.
Error at src/modules/datepicker/helpers/date-fns.ts:53:19: Type 'undefined' cannot be used as an index type.
Error at src/modules/datepicker/helpers/date-fns.ts:54:18: Parameter 'p' implicitly has an 'any' type.
Error at src/modules/datepicker/helpers/date-fns.ts:55:24: Parameter 'pattern' implicitly has an 'any' type.
Error at src/modules/modal/classes/active-modal.ts:7:21: Generic type 'ModalConfig<T, U, undefined, V>' requires 4 type argument(s).
Error at src/modules/modal/classes/active-modal.ts:15:26: Generic type 'ModalConfig<T, U, undefined, V>' requires 4 type argument(s).
Error at src/modules/modal/classes/modal-config.ts:15:31: ',' expected.
Error at src/modules/modal/classes/modal-config.ts:15:46: ',' expected.
Error at src/modules/modal/classes/modal-config.ts:15:48: Duplicate identifier 'undefined'.
Error at src/modules/modal/classes/modal-config.ts:59:39: ',' expected.
Error at src/modules/modal/classes/modal-config.ts:59:54: ',' expected.
Error at src/modules/modal/classes/modal-config.ts:59:56: Duplicate identifier 'undefined'.
Error at src/modules/modal/classes/modal-config.ts:59:75: Generic type 'ModalConfig<T, U, undefined, 
V>' requires 4 type argument(s).
Error at src/modules/modal/classes/modal-config.ts:70:40: ',' expected.
Error at src/modules/modal/classes/modal-config.ts:70:55: ',' expected.
Error at src/modules/modal/classes/modal-config.ts:70:57: Duplicate identifier 'undefined'.
Error at src/modules/modal/classes/modal-config.ts:70:76: Generic type 'ModalConfig<T, U, undefined, V>' requires 4 type argument(s).
Error at src/modules/modal/classes/modal-controls.ts:17:25: ',' expected.
Error at src/modules/modal/classes/modal-controls.ts:17:40: ',' expected.
Error at src/modules/modal/classes/modal-controls.ts:17:42: Duplicate identifier 'undefined'.
Error at src/modules/modal/components/modal.ts:174:24: Supplied parameters do not match any signature of call target.
Error at src/modules/modal/components/modal.ts:227:33: Generic type 'ModalConfig<T, U, undefined, V>' requires 4 type argument(s).
Error at src/modules/modal/services/modal.service.ts:12:32: Generic type 'ModalConfig<T, U, undefined, V>' requires 4 type argument(s).
Error at src/modules/modal/services/modal.service.ts:23:34: Property 'context' does not exist on type 'TemplateModalConfig<any, any, any, any>'.
Error at src/modules/modal/services/modal.service.ts:35:35: Supplied parameters do not match any signature of call target.
Error at src/modules/modal/services/modal.service.ts:35:93: Property 'context' does not exist on type 'ComponentModalConfig<any, any, any, any>'.
Error at src/modules/search/components/search.ts:123:39: Generic type 'LookupFn' requires 2 type argument(s).
Error at src/modules/search/helpers/lookup-fn.ts:3:27: ',' expected.
Error at src/modules/search/helpers/lookup-fn.ts:3:29: Duplicate identifier 'T'.

>

**Comment by sguiheux** [comment]
After installing typescript 2.3.4 in global it works. \o/
