### ISSUE TITLE
Error using the sui-select component in library with angular 6.

### ISSUE THREAD

**Issue by renatovanquish** [edcarroll/ng2-semantic-ui#413]
### Error: Directive ɵcw, Expected 0 arguments, but got 1.

**Example:**
_ng new project-name
cd project-name
ng generate library library-name --prefix=lib
npm install --save ng2-semantic-ui@^0.10.0-alpha.6_

// Import SuiModule in main module and module library
_import {SuiModule} from 'ng2-semantic-ui';_

// Insert sui-select in library-name.component.ts
...
```
  template: `
    <p>
      <sui-select placeholder="Choose">
        <sui-select-option value="Option 1"></sui-select-option>
        <sui-select-option value="Option 2"></sui-select-option>
        <sui-select-option value="Option 3"></sui-select-option>
        <sui-select-option value="Option 4"></sui-select-option>
      </sui-select>
    </p>
  `,
```
....
When I run the build library I get the error message:
**ng build library-name**

```
Building Angular Package
BUILD ERROR
projects/library-name/src/lib/library-name.component.ts.LibraryNameComponent.html(4,5): : Directive ɵcw, Expected 0 arguments, but got 1.

Error: projects/library-name/src/lib/library-name.component.ts.LibraryNameComponent.html(4,5): : Directive ɵcw, Expected 0 arguments, but got 1.

    at analyseEntryPoint (/Users/rtc/htdocs/project-name/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:39:15)
    at MapSubscriber.exports.analyseSourcesTransform.rxjs_1.pipe.operators_1.map.graph [as project] (/Users/rtc/htdocs/project-name/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:15:9)
    at MapSubscriber._next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/operators/map.js:46:35)
    at MapSubscriber.Subscriber.next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/Subscriber.js:64:18)
    at SwitchMapSubscriber.notifyNext (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/operators/switchMap.js:77:26)
    at InnerSubscriber._next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MapSubscriber._next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/operators/map.js:52:26)
    at MapSubscriber.Subscriber.next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/Subscriber.js:64:18)
    at /Users/rtc/htdocs/project-name/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24

projects/library-name/src/lib/library-name.component.ts.LibraryNameComponent.html(4,5): : Directive ɵcw, Expected 0 arguments, but got 1.

Error: projects/library-name/src/lib/library-name.component.ts.LibraryNameComponent.html(4,5): : Directive ɵcw, Expected 0 arguments, but got 1.

    at analyseEntryPoint (/Users/rtc/htdocs/project-name/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:39:15)
    at MapSubscriber.exports.analyseSourcesTransform.rxjs_1.pipe.operators_1.map.graph [as project] (/Users/rtc/htdocs/project-name/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:15:9)
    at MapSubscriber._next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/operators/map.js:46:35)
    at MapSubscriber.Subscriber.next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/Subscriber.js:64:18)
    at SwitchMapSubscriber.notifyNext (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/operators/switchMap.js:77:26)
    at InnerSubscriber._next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MapSubscriber._next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/operators/map.js:52:26)
    at MapSubscriber.Subscriber.next (/Users/rtc/htdocs/project-name/node_modules/rxjs/internal/Subscriber.js:64:18)
    at /Users/rtc/htdocs/project-name/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24

```
Without the sui-select everything works as expected!

my package.json
```
{
  "name": "project-name",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "ng2-semantic-ui": "^0.10.0-alpha.6",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular-devkit/build-ng-packagr": "~0.8.0",
    "@angular/cli": "~6.2.1",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.1.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}
```
I understand that the version is still in development, but I have a project stopped because of this.
Any suggestions on what I can do to resolve this?

**Comment by kunjan343** [comment]
Can you provide stackblitz error generation? May be we can debug the issue.

**Comment by renatovanquish** [comment]
I fixed the problem!
In tsconfig.lib.json i change:
`"angularCompilerOptions": {
....
    "fullTemplateTypeCheck": false,
....
  }`
